#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydbtest
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#
